# Generated by Django 5.1.1 on 2024-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("img_product", models.ImageField(upload_to="img/")),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_id", models.IntegerField()),
                ("number", models.CharField(max_length=20)),
                ("name_customer", models.CharField(max_length=50)),
            ],
        ),
    ]
