# Generated by Django 5.1.1 on 2024-10-06 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserCredential",
            new_name="Member",
        ),
    ]
