# Generated by Django 5.1.1 on 2024-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_product_description_alter_product_img_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order_id",
            field=models.IntegerField(null=True),
        ),
    ]
