# Generated by Django 5.1.1 on 2024-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_product_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="order_id",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("coffee", "Coffee"),
                    ("desserts", "Desserts"),
                    ("breakfast", "Breakfast"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
