# Generated by Django 5.1.1 on 2024-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_order_remove_product_name_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img_product",
            field=models.ImageField(blank=True, null=True, upload_to="myapp/img/"),
        ),
    ]
