# Generated by Django 5.1.1 on 2024-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_product_img_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img_product",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
