# Generated by Django 5.0.7 on 2024-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_product_img_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default="other", max_length=20),
        ),
    ]
