# Generated by Django 5.0.7 on 2024-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_product_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member",
        ),
    ]
