# Generated by Django 5.0.7 on 2024-11-26 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="extra_info",
        ),
    ]
