# Generated by Django 5.0.7 on 2024-12-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_remove_member_extra_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
