# Generated by Django 5.0.7 on 2024-12-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="options",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
