# Generated by Django 5.0.7 on 2024-12-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_product_options_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="options",
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_options",
                        to="myapp.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="options",
            field=models.ManyToManyField(blank=True, to="myapp.option"),
        ),
    ]
