# Generated by Django 5.0.7 on 2024-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_category_delete_addcategory_remove_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
