# Generated by Django 5.0.7 on 2024-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_alter_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("staff", "Staff")],
                default="staff",
                max_length=20,
            ),
        ),
    ]
