# Generated by Django 5.0.7 on 2024-12-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_alter_member_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
