# Generated by Django 5.0.7 on 2025-01-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0023_customermember"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_per_baht",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
            ],
        ),
    ]
