# Generated by Django 5.0.7 on 2025-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0024_pointsconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
