# Generated by Django 5.0.7 on 2025-01-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0026_alter_member_role_store_customermember_store_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="myapp.store",
            ),
        ),
    ]
