# Generated by Django 5.0.7 on 2025-01-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0027_category_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointsconfig",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pointsconfigs",
                to="myapp.store",
            ),
        ),
    ]
