# Generated by Django 5.0.7 on 2025-01-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0030_remove_product_stock_order_products_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productingredient",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productingredients",
                to="myapp.store",
            ),
        ),
    ]
