# Generated by Django 5.0.7 on 2025-01-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0033_promotion_product_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="products",
            field=models.ManyToManyField(related_name="promotions", to="myapp.product"),
        ),
    ]
