# Generated by Django 5.0.7 on 2025-01-25 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0034_promotion_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="products",
        ),
    ]
