# Generated by Django 5.0.7 on 2025-01-25 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0035_remove_promotion_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="products",
            field=models.ManyToManyField(related_name="promotions", to="myapp.product"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="myapp.store",
            ),
        ),
    ]
