# Generated by Django 5.0.7 on 2025-01-25 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0036_promotion_products_promotion_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="products",
        ),
    ]
