# Generated by Django 5.0.7 on 2025-01-28 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0038_member_login_time_member_logout_time_order_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="total_login_time",
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name="member",
            name="total_logout_time",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
