# Generated by Django 5.0.7 on 2025-01-29 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0039_member_total_login_time_member_total_logout_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="login_time",
        ),
        migrations.RemoveField(
            model_name="member",
            name="logout_time",
        ),
        migrations.RemoveField(
            model_name="member",
            name="total_login_time",
        ),
        migrations.RemoveField(
            model_name="member",
            name="total_logout_time",
        ),
    ]
