# Generated by Django 5.0.7 on 2025-02-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0040_remove_member_login_time_remove_member_logout_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointsconfig",
            name="points_to_baht",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
