# Generated by Django 5.0.7 on 2025-02-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0041_pointsconfig_points_to_baht"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="points_used",
            field=models.IntegerField(default=0),
        ),
    ]
