# Generated by Django 5.0.7 on 2025-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0042_order_points_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
