# Generated by Django 5.0.7 on 2025-02-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0043_option_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="options",
            field=models.ManyToManyField(
                blank=True, related_name="order_details", to="myapp.option"
            ),
        ),
        migrations.CreateModel(
            name="OrderOptionQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.option"
                    ),
                ),
                (
                    "order_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.orderdetail",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="option_quantity",
            field=models.ManyToManyField(
                related_name="order_option_quantities",
                through="myapp.OrderOptionQuantity",
                to="myapp.option",
            ),
        ),
    ]
