# Generated by Django 5.0.7 on 2025-02-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0044_alter_orderdetail_options_orderoptionquantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="option_quantity",
        ),
        migrations.RemoveField(
            model_name="option",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="options",
        ),
        migrations.CreateModel(
            name="OrderDetailOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.option"
                    ),
                ),
                (
                    "order_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_detail_options",
                        to="myapp.orderdetail",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OrderOptionQuantity",
        ),
    ]
