"""
Django settings for myposapp project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1ld-7lwv(ssha7oylf7vfn05)jek20w=3r1gv4+#+niu8###^u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'tailwind',
    'theme',
    'django_browser_reload',
    'django_dbml',
    'myapp',
]
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "myposapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'myapp.context_processors.user_store_info',  # Add this line
            ],
        },
    },
]

WSGI_APPLICATION = "myposapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": 'django.db.backends.mysql',
        "NAME": "posdb",
        "USER": "Got",
        "PASSWORD": "1234",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    },
    'sqlite3': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}
DATABASES['default'] = DATABASES['sqlite3']
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "th"

TIME_ZONE = "Asia/Bangkok"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"

# กำหนดเส้นทางเพิ่มเติมสำหรับ static files (เช่น รูปภาพ ไฟล์ CSS, JavaScript ที่จะไม่ถูกเก็บใน media)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'img'),  # ใส่เส้นทางไปยัง static files ที่ต้องการจัดเก็บเพิ่มเติม
]
# Media files (ไฟล์ที่ผู้ใช้สามารถอัปโหลดได้ เช่น รูปภาพ, ไฟล์เสียง, วิดีโอ)
MEDIA_URL = '/media/'  # URL สำหรับเข้าถึงไฟล์ media
MEDIA_ROOT = os.path.join(BASE_DIR, 'img')  # เส้นทางในระบบไฟล์ของโปรเจกต์


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # หรือโฮสต์ SMTP ที่คุณใช้
EMAIL_PORT = 587  # ใช้ 587 สำหรับ TLS หรือ 465 สำหรับ SSL
EMAIL_USE_TLS = True  # ถ้าใช้ TLS
EMAIL_HOST_USER = 'wachirawit.sa.65@ubu.ac.th'  # อีเมลผู้ส่ง
EMAIL_HOST_PASSWORD = 'lmjg ttaa xcvb kuda'  # รหัสผ่านของอีเมล
DEFAULT_FROM_EMAIL = 'wachirawit.sa.65@ubu.ac.th'

STRIPE_SECRET_KEY = 'sk_test_51QkIQsKTyjDLYfcr8xHecyo8rUk3vdRcO3hO8jdT8GuMaAHepUeC7YRC0kZ9LR31Bkj6ZgvB3fXCe1gZfb1CVraX00BpCUlNcM'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51QkIQsKTyjDLYfcrCE7l2JjSCSkhI3xZOY1NpDp1plRrX5Jmo01JwTwRjnBWJGStU3dsjhw4LXzeByfInLzRA5D800KB131a1y'