#myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('order/', views.Order1, name='order'),
    path('payment/<int:order_id>/', views.PayMent, name='payment'),
    path('marketing/', views.Marketing, name='Marketing'),
    path('history/', views.History_Order, name='History_Order'),
    path('member/', views.Member1, name='member'),
    path('edit_member/<int:member_id>/', views.edit_member, name='edit_member'),
    path('delete_member/<int:member_id>/', views.delete_member, name='delete_member'),
    path('addmenu/', views.Addmenu, name='addmenu'),
    #path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('add_to_order/', views.add_to_order, name='add_to_order'),  # เพิ่มเส้นทางสำหรับเพิ่มสินค้าใน order
    path('complete_order/<int:order_id>/', views.complete_order, name='complete_order'),
    path('update_order_detail/', views.update_order_detail, name='update_order_detail'),
    path('delete_order_detail/', views.delete_order_detail, name='delete_order_detail'),
    path('paynow/<int:order_id>/', views.PayNow, name='paynow'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('add_category/', views.add_category, name='add_category'),
    path('edit_category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('get_order_details/<int:order_id>/', views.get_order_details, name='get_order_details'),
    path('search_member/', views.search_member, name='search_member'),
    path('update-points-config/', views.update_points_config, name='update_points_config'),
    path('order/<int:order_id>/print/', views.print_receipt, name='print_receipt'),
    path('manage_ingredients/', views.manage_ingredients, name='manage_ingredients'),
    path('edit_ingredient/<int:ingredient_id>/', views.edit_ingredient, name='edit_ingredient'),
    path('delete_ingredient/<int:ingredient_id>/', views.delete_ingredient, name='delete_ingredient'),
    path('add_ingredient/', views.add_ingredient, name='add_ingredient'),
    path('product/<int:product_id>/ingredients/', views.manage_product_ingredients, name='manage_product_ingredients'),
    path('product-ingredient/delete/<int:ingredient_id>/', views.delete_product_ingredient, name='delete_product_ingredient'),
    path('product-ingredient/edit/<int:ingredient_id>/', views.edit_product_ingredient, name='edit_product_ingredient'),
    path('manage_ingredients_list', views.manage_product_ingredient_list, name='manage_product_ingredients_list'),
    path('promotions/', views.manage_promotions, name='manage_promotions'),
    path('promotions/add/', views.add_promotion, name='add_promotion'),
    path('promotions/update/<int:product_id>/', views.update_product_promotion, name='update_product_promotion'),
    path('promotions/edit/<int:promotion_id>/', views.edit_promotion, name='edit_promotion'),
    path('promotions/delete/<int:promotion_id>/', views.delete_promotion, name='delete_promotion'),
    path('employees/', views.manage_employees, name='manage_employees'),
    path('employees/add/', views.add_employee, name='add_employee'),
    path('employees/edit/<int:employee_id>/', views.edit_employee, name='edit_employee'),
    path('employees/delete/<int:employee_id>/', views.delete_employee, name='delete_employee'),
    path('employee_performance/<int:employee_id>/', views.employee_performance, name='employee_performance'),
    path('top_employees/', views.top_employees, name='top_employees'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
